spring:
  datasource:
#    url: jdbc:postgresql://192.168.1.8:5432/loldb
    url: jdbc:postgresql://localhost:5432/rental_store
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
