server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

#logging:
#  level:
#    org.springframework.cloud.bootstrap: DEBUG
#    org.springframework.boot.context.config: DEBUG


# CONFIG SERVER
#spring:
#  application:
#    name: EUREKA-SERVER
#  config:
#    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888