spring:
  application:
    name: INVENTORY-SERVICE
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888
# Retry Config-Server?
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        multiplier: 1.5