server:
  port: 9090

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Abilita la scoperta dei servizi via Eureka
          lower-case-service-id: true
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**

#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/products/**

eureka:
  client:
    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#      defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
