server:
  port: 8082
  servlet:
    context-path: /api/inventory

spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/inventory
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
